//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubirFotoWebBrazalete.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>kisin</string>
  <string>2012foto</string>
  <string>FOTEX</string>
  <string>10.248.1.141</string>
  <string>50.97.211.130</string>
  <string>fotoxcaretuser</string>
  <string>mGcwH762</string>
  <string>http://10.1.5.82:8888/Media</string>
  <string>http://xcshpbld14/xcfotohist2/</string>
  <string>fotoxcaret.com/httpdocs/fotos/2</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ConexionXcaret {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ConexionXcaret"]));
            }
            set {
                this["ConexionXcaret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>xhkisin</string>
  <string>2014foto</string>
  <string>XHFOTEX</string>
  <string>192.168.41.37</string>
  <string>184.172.99.66</string>
  <string>fotouserxelha3</string>
  <string>U6GMVP81_MM1</string>
  <string>http://192.168.41.38/XTABAY/Fotografias</string>
  <string>http://192.168.41.38/FotoHistorico</string>
  <string>photoxelha.com/httpdocs/datos/fotos/2</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ConexionXelha {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ConexionXelha"]));
            }
            set {
                this["ConexionXelha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>xnkisin</string>
  <string>2014foto</string>
  <string>XNFOTEX</string>
  <string>10.248.1.222</string>
  <string>50.97.211.130</string>
  <string>fotoxcaretuser</string>
  <string>mGcwH762</string>
  <string>http://10.1.5.82:8888/Media</string>
  <string>http://xcshpbld14/xcfotohist2/</string>
  <string>fotoxcaret.com/httpdocs/fotos/2</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ConexionXenotes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ConexionXenotes"]));
            }
            set {
                this["ConexionXenotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>xmkisin</string>
  <string>2014foto</string>
  <string>XMFOTEX</string>
  <string>10.250.1.21</string>
  <string>50.97.211.130</string>
  <string>fotoxcaretuser</string>
  <string>mGcwH762</string>
  <string>http://10.1.5.82:8888/Media</string>
  <string>http://xcshpbld14/xcfotohist2/</string>
  <string>fotoxcaret.com/httpdocs/fotos/2</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ConexionXoximilco {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ConexionXoximilco"]));
            }
            set {
                this["ConexionXoximilco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>xpkisin</string>
  <string>2014foto</string>
  <string>XPFOTEX</string>
  <string>10.1.5.83</string>
  <string>50.97.211.130</string>
  <string>fotoxcaretuser</string>
  <string>mGcwH762</string>
  <string>http://10.1.5.82:8888/Media</string>
  <string>http://xcshpbld14/xcfotohist2/</string>
  <string>fotoxcaret.com/httpdocs/fotos/2</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ConexionXplor {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ConexionXplor"]));
            }
            set {
                this["ConexionXplor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>xpkisin</string>
  <string>2014foto</string>
  <string>XFFOTEX</string>
  <string>10.248.1.92</string>
  <string>50.97.211.130</string>
  <string>fotoxcaretuser</string>
  <string>mGcwH762</string>
  <string>http://10.1.5.82:8888/Media</string>
  <string>http://xcshpbld14/xcfotohist2/</string>
  <string>fotoxcaret.com/httpdocs/fotos/2</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ConexionXplorFuego {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ConexionXplorFuego"]));
            }
            set {
                this["ConexionXplorFuego"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>kisin</string>
  <string>WO37fNvKcH6eK3P5oJZW</string>
  <string>dbFotex</string>
  <string>10.1.5.73</string>
  <string>50.97.211.130</string>
  <string>fotoxcaretuser</string>
  <string>mGcwH762</string>
  <string>http://10.1.5.82:8888/Media</string>
  <string>http://xcshpbld14/xcfotohist2/</string>
  <string>fotoxcaret.com/httpdocs/fotos/2</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ConexionXenses {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ConexionXenses"]));
            }
            set {
                this["ConexionXenses"] = value;
            }
        }
    }
}
